"""Generate the Supplemental Material LaTeX tables from the archived results.

Every number in the Supplemental Material tables is emitted from the JSON/CSV
files written by ``run_all.py``; none is transcribed by hand.  Running

    python src/make_sm_tables.py

rewrites the ``sm_tab_*.tex`` fragments that ``supplement.tex`` inputs.
"""

from __future__ import annotations

import csv
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent          # .../PRA/code
RESULTS = ROOT / "results"
LOGS = ROOT / "logs"
OUT = ROOT.parent / "article" / "sections"


# ---------------------------------------------------------------------------
# formatting helpers
# ---------------------------------------------------------------------------
def sci(x, sig=2):
    """Render x as $m\\times10^{e}$ with `sig` significant digits."""
    if x is None:
        return "---"
    if x == 0:
        return "$0$"
    s = f"{x:.{sig}e}"
    mant, exp = s.split("e")
    exp = int(exp)
    if exp == 0:
        return f"${mant}$"
    return "$" + mant + r"\times10^{" + str(exp) + "}$"


def integer(x):
    return "---" if x is None else f"${int(x)}$"


def write(name, body):
    path = OUT / name
    path.write_text(body, encoding="ascii", newline="\n")
    print(f"wrote {path.name}  ({len(body)} chars)")


def load_json(p):
    with open(p, encoding="utf-8") as fh:
        return json.load(fh)


NL = "\\\\\n"
COLRULE = "\\colrule\n"


# ---------------------------------------------------------------------------
# S1 -- trajectory PINN training protocol
# ---------------------------------------------------------------------------
def table_s1():
    keys = ["stable", "growing", "pullin"]
    cfg, par, wall, loss = {}, {}, {}, {}
    for key in keys:
        h = load_json(LOGS / f"history_{key}.json")
        cfg[key], par[key] = h["config"], h["params"]
        wall[key] = h["wall_time"]
        loss[key] = h["L_total"][-1]

    def row(label, fn):
        return label + " & " + " & ".join(fn(k) for k in keys) + NL

    b = []
    b.append("% generated by code/src/make_sm_tables.py -- do not edit by hand\n")
    b.append("\\begin{table}[htb]\n")
    b.append("\\caption{\\label{tab:S1}%\n")
    b.append("Training protocol of the three single-trajectory physics-informed\n")
    b.append("neural networks. All runs are CPU-only, in double precision, and\n")
    b.append("seeded with $42$. Wall-clock times were measured on one core.}\n")
    b.append("\\begin{ruledtabular}\n")
    b.append("\\begin{tabular}{lccc}\n")
    b.append("Setting & Stable & Growing & Pull-in" + NL + COLRULE)
    b.append(row("Parametrization", lambda k: cfg[k]["parametrization"]))
    b.append(row("$\\alpha$", lambda k: f"${par[k]['alpha']:.6g}$"))
    b.append(row("$\\beta$", lambda k: sci(par[k]["beta"], 3)
                 if par[k]["beta"] < 1e-2 else f"${par[k]['beta']:.6g}$"))
    b.append(row("$\\zeta$", lambda k: f"${par[k]['zeta']:g}$"))
    b.append(row("Training window $T$", lambda k: f"${par[k]['T']:.4g}$"))
    b.append(row("Hidden layers", lambda k: integer(cfg[k]["n_hidden"])))
    b.append(row("Width", lambda k: integer(cfg[k]["width"])))
    b.append(row("Fourier modes", lambda k: integer(cfg[k]["n_fourier"])))
    b.append(row("Fourier $\\omega$", lambda k: f"${cfg[k]['fourier_omega']:g}$"))
    b.append(row("Collocation $N$", lambda k: integer(cfg[k]["n_collocation"])))
    b.append(row("Adam steps", lambda k: integer(cfg[k]["adam_iters"])))
    b.append(row("Adam rate", lambda k: sci(cfg[k]["adam_lr"], 1)))
    b.append(row("L-BFGS steps", lambda k: integer(cfg[k]["lbfgs_iters"])))
    b.append(row("Final loss", lambda k: sci(loss[k], 2)))
    b.append(row("Wall clock (s)", lambda k: f"${wall[k]:.0f}$"))
    b.append("\\end{tabular}\n\\end{ruledtabular}\n\\end{table}\n")
    write("sm_tab_s1_training.tex", "".join(b))


# ---------------------------------------------------------------------------
# S2 -- parametric fold PINN
# ---------------------------------------------------------------------------
def table_s2():
    d = load_json(LOGS / "pinn_boundary.json")
    n, m = d["network"], d["metrics"]
    rows = [
        ("Input dimension", integer(n["params_in"])),
        ("Hidden layers", integer(n["depth"])),
        ("Width", integer(n["width"])),
        ("Collocation points", integer(n["collocation"])),
        ("Adam steps", integer(n["adam_iters"])),
        ("L-BFGS steps", integer(n["lbfgs_iters"])),
        ("Final residual loss", sci(d["final_residual_loss"], 2)),
        ("Wall clock (s)", f"${d['wall_time_train_s']:.0f}$"),
        (COLRULE + "RMSE of the pull-in gap $u_*$", sci(m["u_field_rmse"], 2)),
        ("Maximum $|\\Delta u_*|$", sci(m["u_field_max_abs"], 2)),
        ("Mean $|\\Delta\\alpha|$ on the fold", sci(m["boundary_mean_abs_dalpha"], 2)),
        ("Maximum $|\\Delta\\alpha|$ on the fold", sci(m["boundary_max_abs_dalpha"], 2)),
        ("$\\alpha_c$ at $\\beta=0$, surrogate", f"${m['alpha_c_beta0_pinn']:.7f}$"),
        ("$\\alpha_c$ at $\\beta=0$, exact $4/27$", f"${m['alpha_c_beta0_ref']:.7f}$"),
        ("$\\beta^{*}$ at $\\alpha=0$, surrogate", f"${m['beta_c_alpha0_pinn']:.7f}$"),
        ("$\\beta^{*}$ at $\\alpha=0$, exact $256/3125$",
         f"${m['beta_c_alpha0_ref']:.7f}$"),
        ("Cells matching the static fold (\\%)",
         f"${m['grid_acc_vs_static_pct']:.2f}$"),
        ("Cells matching from-rest RK4 (\\%)",
         f"${m['grid_acc_vs_rk4_pct']:.2f}$"),
    ]
    b = ["% generated by code/src/make_sm_tables.py -- do not edit by hand\n",
         "\\begin{table}[htb]\n",
         "\\caption{\\label{tab:S2}%\n",
         "Parametric equilibrium surrogate: architecture, optimization, and\n",
         "accuracy against the closed-form fold of the main text. The last two\n",
         "rows classify each cell of an $(\\alpha,\\beta)$ grid as pull-in or\n",
         "stable.}\n",
         "\\begin{ruledtabular}\n\\begin{tabular}{lc}\n",
         "Quantity & Value" + NL + COLRULE]
    for label, val in rows:
        b.append(f"{label} & {val}" + NL)
    b.append("\\end{tabular}\n\\end{ruledtabular}\n\\end{table}\n")
    write("sm_tab_s2_foldpinn.tex", "".join(b))


# ---------------------------------------------------------------------------
# S3 -- phase-diagram numerics
# ---------------------------------------------------------------------------
def table_s3():
    d = load_json(LOGS / "phase_diagram.json")
    g, it = d["grid"], d["integration"]
    p, c = d["summary_primary"], d["summary_compare"]
    eps = sci(it["eps_barrier"], 0).strip("$")
    esc = sci(it["escape_low"], 0).strip("$")
    rows = [
        ("Grid in $\\alpha$", f"${g['n_alpha']}$ points on "
         f"$[{g['alpha_range'][0]:g},{g['alpha_range'][1]:g}]$"),
        ("Grid in $\\beta$", f"${g['n_beta']}$ points on "
         f"$[{g['beta_range'][0]:g},{g['beta_range'][1]:g}]$"),
        ("Integrator", "fixed-step RK4"),
        ("Step $\\Delta\\tau$", f"${it['dt']:g}$"),
        ("Horizon $\\tau_{\\max}$", f"${it['t_max']:g}$"),
        ("Pull-in criterion", f"$\\xi\\ge1-\\epsilon$, $\\epsilon={eps}$"),
        ("Escape guard", f"$\\xi<{esc}$"),
        ("Cells that escaped", integer(p["n_escaped"])),
        (COLRULE + "Damping $\\zeta$", f"${d['zeta_primary']:g}$"),
        ("Dynamic pull-in fraction", f"${p['fraction_pullin_dynamic']:.4f}$"),
        ("Static pull-in fraction", f"${p['fraction_pullin_static']:.4f}$"),
        ("Overshoot band, fraction of cells",
         f"${p['overshoot_cell_fraction']:.4f}$"),
        ("Mean gap $\\Delta\\alpha$", f"${p['mean_alpha_gap']:.5f}$"),
        ("Median gap $\\Delta\\alpha$", f"${p['median_alpha_gap']:.5f}$"),
        ("Maximum gap $\\Delta\\alpha$", f"${p['max_alpha_gap']:.5f}$"),
        ("Boundary samples", integer(p["n_boundary_rows"])),
        ("Range of $\\tau_{\\mathrm{PI}}$",
         f"${p['tau_pullin_min']:.2f}$--${p['tau_pullin_max']:.2f}$"),
        (COLRULE + "Damping $\\zeta$", f"${d['zeta_compare']:g}$"),
        ("Dynamic pull-in fraction", f"${c['fraction_pullin_dynamic']:.4f}$"),
        ("Mean gap $\\Delta\\alpha$", sci(c["mean_alpha_gap"], 2)),
        (COLRULE + "Fold endpoint $\\alpha_c(\\beta=0)$",
         f"${d['fold_endpoints']['alpha_c_beta0']:.6f}$"),
        ("Fold endpoint $\\beta^{*}(\\alpha=0)$",
         f"${d['fold_endpoints']['beta_star']:.6f}$"),
        ("Integration time (s)",
         f"${d['integration_time_primary_s']:.0f}$ and "
         f"${d['integration_time_compare_s']:.0f}$"),
    ]
    b = ["% generated by code/src/make_sm_tables.py -- do not edit by hand\n",
         "\\begin{table}[htb]\n",
         "\\caption{\\label{tab:S3}%\n",
         "Construction of the pull-in phase diagram of the main text. Each grid\n",
         "cell is integrated from rest until the gap closes or the horizon is\n",
         "reached. The gap $\\Delta\\alpha$ is the horizontal offset between the\n",
         "dynamic boundary and the static fold.}\n",
         "\\begin{ruledtabular}\n\\begin{tabular}{lc}\n",
         "Quantity & Value" + NL + COLRULE]
    for label, val in rows:
        b.append(f"{label} & {val}" + NL)
    b.append("\\end{tabular}\n\\end{ruledtabular}\n\\end{table}\n")
    write("sm_tab_s3_phase.tex", "".join(b))


# ---------------------------------------------------------------------------
# S4 -- fixed-step RK4 step study
# ---------------------------------------------------------------------------
def table_s4():
    with open(RESULTS / "rk4_stepstudy.csv", encoding="utf-8") as fh:
        rows = list(csv.DictReader(fh))
    b = ["% generated by code/src/make_sm_tables.py -- do not edit by hand\n",
         "\\begin{table}[htb]\n",
         "\\caption{\\label{tab:S4}%\n",
         "Fixed-step fourth-order Runge--Kutta at the movable pole, for the\n",
         "pull-in case $\\alpha=0.2$, $\\beta=0.1$, $\\zeta=0.5$. The error column\n",
         "is the sup-norm in $\\xi$ over $[0,0.98\\tau_*]$, away from the pole;\n",
         "$\\xi_{\\max}$ is the largest finite value reached after the scheme\n",
         "steps past $\\xi=1$. Every step size overshoots.}\n",
         "\\begin{ruledtabular}\n\\begin{tabular}{cccccc}\n",
         "$h$ & Steps & $E_\\infty(\\xi)$ & $\\tau_{\\mathrm{PI}}$ & "
         "$|\\Delta\\tau_{\\mathrm{PI}}|$ & $\\xi_{\\max}$" + NL + COLRULE]
    for r in rows:
        b.append(
            f"${float(r['h']):g}$ & {int(r['n_steps'])} & "
            + sci(float(r["linf_xi_[0,0.98tau*]"]), 2) + " & "
            + f"${float(r['tau_PI_est']):.4f}$ & "
            + sci(float(r["tau_PI_err"]), 2) + " & "
            + f"${float(r['xi_max_finite']):.0f}$" + NL)
    b.append("\\end{tabular}\n\\end{ruledtabular}\n\\end{table}\n")
    write("sm_tab_s4_rk4.tex", "".join(b))


# ---------------------------------------------------------------------------
# S5 -- autodiff sensitivities; S6 -- inverse design
# ---------------------------------------------------------------------------
def table_s5():
    d = load_json(RESULTS / "inverse_design.json")
    blocks = [("A", d["demo1_sensitivities"]["V_PI_sensitivities"]),
              ("B", d["demo1_sensitivities"]["V_PI_sensitivities_deviceB"])]
    b = ["% generated by code/src/make_sm_tables.py -- do not edit by hand\n",
         "\\begin{table*}[htb]\n",
         "\\caption{\\label{tab:S5}%\n",
         "Design sensitivities of the pull-in voltage taken by automatic\n",
         "differentiation through the fold surrogate, against a finite-difference\n",
         "evaluation of the closed-form fold, at the two devices that bracket the\n",
         "Casimir loading of Table~I. Device~A carries $\\beta=0.026$ and\n",
         "device~B $\\beta=0.052$. The elasticity is\n",
         "$\\partial\\ln V_{\\mathrm{PI}}/\\partial\\ln p$.}\n",
         "\\begin{ruledtabular}\n\\begin{tabular}{llcccc}\n",
         "Device & Derivative & Surrogate & Reference & Rel. error & Elasticity"
         + NL + COLRULE]
    labels = [
        ("dV_dd", "$\\partial V_{\\mathrm{PI}}/\\partial d$ (V/m)"),
        ("dV_dA", "$\\partial V_{\\mathrm{PI}}/\\partial A$ (V/m$^{2}$)"),
        ("dV_dk", "$\\partial V_{\\mathrm{PI}}/\\partial k$ (Vm/N)"),
    ]
    for name, blk in blocks:
        comp = blk["components"]
        for j, (key, lab) in enumerate(labels):
            c = comp[key]
            b.append((name if j == 0 else "") + " & " + lab + " & "
                     + sci(c["surrogate"], 4) + " & "
                     + sci(c["analytic_fd"], 4) + " & " + sci(c["rel_err"], 1)
                     + f" & ${c['elasticity_surrogate']:.4f}$" + NL)
        if name == "A":
            b.append(COLRULE)
    b.append("\\end{tabular}\n\\end{ruledtabular}\n\\end{table*}\n")
    write("sm_tab_s5_sensitivity.tex", "".join(b))


def table_s6():
    d = load_json(RESULTS / "inverse_design.json")
    inv = d["demo2_inverse_design"]
    rows = [
        ("Recovered gap $d$ (nm)", f"${inv['recovered']['d_nm']:.5f}$"),
        ("Closed-form gap $d$ (nm)", f"${inv['analytic']['d_nm']:.5f}$"),
        ("Absolute error in $d$ (nm)", sci(inv["error"]["abs_err_d_nm"], 2)),
        ("Recovered $\\beta$", f"${inv['recovered']['beta']:.6f}$"),
        ("Absolute error in $V_{\\mathrm{PI}}$ (V)",
         sci(inv["error"]["abs_err_V_PI_V"], 2)),
        ("Adam steps to tolerance", integer(inv["convergence"]["iters_to_tol"])),
        ("Wall clock (ms)", f"${inv['convergence']['wall_time_to_best_ms']:.0f}$"),
        ("Final objective", sci(inv["convergence"]["final_loss"], 2)),
    ]
    b = ["% generated by code/src/make_sm_tables.py -- do not edit by hand\n",
         "\\begin{table}[htb]\n",
         "\\caption{\\label{tab:S6}%\n",
         "Gradient-based inverse design through the same surrogate: the smallest\n",
         "gap that still holds a target pull-in voltage of\n",
         "$0.30\\,\\mathrm{V}$ at fixed area and stiffness.}\n",
         "\\begin{ruledtabular}\n\\begin{tabular}{lc}\n",
         "Quantity & Value" + NL + COLRULE]
    for label, val in rows:
        b.append(f"{label} & {val}" + NL)
    b.append("\\end{tabular}\n\\end{ruledtabular}\n\\end{table}\n")
    write("sm_tab_s6_inverse.tex", "".join(b))


# ---------------------------------------------------------------------------
# S7 -- device parameters (regenerated whenever device_table.csv changes)
# ---------------------------------------------------------------------------
def table_s7():
    with open(RESULTS / "device_table.csv", encoding="utf-8") as fh:
        rows = list(csv.DictReader(fh))
    b = ["% generated by code/src/make_sm_tables.py -- do not edit by hand\n",
         "\\begin{table*}[htb]\n",
         "\\caption{\\label{tab:S7}%\n",
         "Parameters of the representative devices. The Casimir strength is\n",
         "$\\beta=\\pi^{2}\\hbar cA/(240kd^{5})$ and the effective mass follows\n",
         "from $k$ and $f_0$. The last column is the classical-limit thermal\n",
         "bound on the pull-in voltage at $300\\,\\mathrm{K}$ derived in the\n",
         "Appendix.}\n",
         "\\begin{ruledtabular}\n\\begin{tabular}{llcccccccc}\n",
         "Device & Description & $A$ ($\\mu\\mathrm{m}^{2}$) & $d$ (nm) & "
         "$k$ (N/m) & $Q$ & $\\beta$ & $\\xi_{\\mathrm{PI}}$ & "
         "$V_{\\mathrm{PI}}$ (V) & $\\Delta V_{\\mathrm{PI}}$ (\\%)"
         + NL + COLRULE]
    for r in rows:
        b.append(
            f"{r['name']} & {r['desc']} & ${float(r['A_um2']):g}$ & "
            f"${float(r['d_nm']):g}$ & ${float(r['k_N_per_m']):g}$ & "
            f"${float(r['Q']):g}$ & ${float(r['beta']):.5f}$ & "
            f"${float(r['xi_pi_T0']):.4f}$ & ${float(r['V_PI_0K']):.4f}$ & "
            f"${float(r['dV_PI_pct']):.2f}$" + NL)
    b.append("\\end{tabular}\n\\end{ruledtabular}\n\\end{table*}\n")
    write("sm_tab_s7_devices.tex", "".join(b))


def table_s8():
    with open(RESULTS / "band_scan.csv", encoding="utf-8") as fh:
        rows = list(csv.DictReader(fh))
    b = ["% generated by code/src/make_sm_tables.py -- do not edit by hand\n",
         "\\begin{table}[htb]\n",
         "\\caption{\\label{tab:S8}%\n",
         "Closure of the kinetic-overshoot band with damping, at $\\beta=0$.\n",
         "The width is $\\alpha_c-\\alpha_{\\mathrm{dyn}}$, located by bisection on\n",
         "the crossing of the saddle. The last column is the quadratic law\n",
         "$0.167\\,(\\zeta_c-\\zeta)^{2}$ with $\\zeta_c=0.3959$, fitted over\n",
         "$\\zeta\\ge0.20$.}\n",
         "\\begin{ruledtabular}\n\\begin{tabular}{ccc}\n",
         "$\\zeta$ & $\\alpha_c-\\alpha_{\\mathrm{dyn}}$ & quadratic law"
         + NL + COLRULE]
    for r in rows:
        b.append(f"${float(r['zeta']):.2f}$ & "
                 + sci(float(r["band_width"]), 3) + " & "
                 + sci(float(r["quadratic_fit"]), 3) + NL)
    b.append("\\end{tabular}\n\\end{ruledtabular}\n\\end{table}\n")
    write("sm_tab_s8_bandscan.tex", "".join(b))


if __name__ == "__main__":
    OUT.mkdir(parents=True, exist_ok=True)
    table_s1()
    table_s2()
    table_s3()
    table_s4()
    table_s5()
    table_s6()
    table_s7()
    table_s8()
